import type { ModuleDefinition } from "./types";

/**
 * The full Ci Business OS module map — the master blueprint, expressed as
 * data instead of a document. This is what the sidebar, the command
 * palette, the "Ask CI" router and (eventually) permissions all read from.
 *
 * `status`:
 *   - "live"        implemented in this codebase with real interactive UI
 *   - "scaffolded"  has a route and placeholder screen
 *   - "planned"     registered so the shape of the OS is complete; not built
 *
 * 16 modules are wired up end-to-end so far, sharing one dataset
 * (src/lib/data.ts) rather than being isolated demos. The rest are
 * registered and navigable but not yet built — see MODULES.md for the
 * always-current live count and full breakdown by category.
 */
export const MODULES: ModuleDefinition[] = [
  { id: "ci-home", slug: "home", name: "CI Home", category: "home", status: "live",
    description: "Universal command bar, dashboard, notifications, approvals, global search, Ask CI.",
    keywords: ["dashboard", "home", "command center", "overview"] },
  { id: "ci-desktop", slug: "desktop", name: "CI Desktop", category: "home", status: "planned",
    description: "The unified PC interface: launcher, windows/workspaces, clipboard, screenshots.",
    keywords: ["desktop", "launcher", "workspace"] },
  { id: "ci-mobile", slug: "mobile", name: "CI Mobile", category: "home", status: "planned",
    description: "Companion mobile environment for approvals, mail, CRM, scanner and alerts.",
    keywords: ["mobile", "app", "companion"] },

  // ── Work ────────────────────────────────────────────────────────────
  { id: "ci-docs", slug: "docs", name: "CI Docs", replaces: "Word", category: "work", status: "live",
    description: "Documents, templates, track changes, versioning, AI rewriting, DOCX/PDF import-export.",
    keywords: ["document", "word", "writing", "template"] },
  { id: "ci-sheets", slug: "sheets", name: "CI Sheets", replaces: "Excel", category: "work", status: "live",
    description: "Spreadsheets, formulas, pivot tables, forecasting, AI formula creation.",
    keywords: ["spreadsheet", "excel", "formula", "pivot"] },
  { id: "ci-present", slug: "present", name: "CI Present", replaces: "PowerPoint", category: "work", status: "planned",
    description: "Presentations, themes, automatic slide generation, brand enforcement.",
    keywords: ["slides", "powerpoint", "presentation", "deck"] },
  { id: "ci-pdf", slug: "pdf", name: "CI PDF", replaces: "Acrobat", category: "work", status: "planned",
    description: "View, convert, merge, split, OCR, redact, sign and extract from PDFs.",
    keywords: ["pdf", "acrobat", "ocr", "merge"] },
  { id: "ci-notes", slug: "notes", name: "CI Notes", category: "work", status: "planned",
    description: "Quick notes, notebooks, clippings, voice-to-note, handwriting OCR.",
    keywords: ["notes", "notebook", "memo"] },
  { id: "ci-forms", slug: "forms", name: "CI Forms", category: "work", status: "planned",
    description: "Form builder, surveys, conditional logic, automatic workflow triggering.",
    keywords: ["form", "survey", "questionnaire"] },
  { id: "ci-tasks", slug: "tasks", name: "CI Tasks", category: "work", status: "live",
    description: "To-dos, assignments, priorities, deadlines, recurring tasks, approvals.",
    keywords: ["task", "todo", "checklist", "reminder"] },

  // ── Communicate ─────────────────────────────────────────────────────
  { id: "ci-mail", slug: "mail", name: "CI Mail", replaces: "Outlook", category: "communicate", status: "live",
    description: "Multi-account mail, rules, shared mailboxes, smart replies, phishing detection.",
    keywords: ["email", "outlook", "inbox", "mail"] },
  { id: "ci-calendar", slug: "calendar", name: "CI Calendar", category: "communicate", status: "live",
    description: "Scheduling, rooms/resources, availability, booking links, meeting prep.",
    keywords: ["calendar", "schedule", "meeting", "booking"] },
  { id: "ci-contacts", slug: "contacts", name: "CI Contacts", category: "communicate", status: "live",
    description: "People, companies, relationship history, dedupe, customer/supplier links.",
    keywords: ["contacts", "people", "address book"] },
  { id: "ci-chat", slug: "chat", name: "CI Chat", replaces: "Teams / Slack", category: "communicate", status: "planned",
    description: "DMs, channels, threads, mentions, searchable history, AI summaries.",
    keywords: ["chat", "slack", "teams", "messaging"] },
  { id: "ci-meet", slug: "meet", name: "CI Meet", category: "communicate", status: "planned",
    description: "Video meetings, captions, transcription, action items, auto summaries.",
    keywords: ["meeting", "video call", "zoom", "transcription"] },
  { id: "ci-communications", slug: "communications", name: "CI Communications", category: "communicate", status: "planned",
    description: "SMS, business messaging, notifications, unified conversation history.",
    keywords: ["sms", "whatsapp", "messaging"] },
  { id: "ci-notifications", slug: "notifications", name: "CI Notifications", category: "communicate", status: "live",
    description: "Central notification engine: priority, snooze, digest, escalation.",
    keywords: ["notifications", "alerts"] },

  // ── Files ───────────────────────────────────────────────────────────
  { id: "ci-drive", slug: "drive", name: "CI Drive", replaces: "OneDrive / Dropbox", category: "files", status: "live",
    description: "Files, folders, sharing, permissions, version history, team spaces.",
    keywords: ["drive", "storage", "files", "dropbox", "onedrive"] },
  { id: "ci-search", slug: "search", name: "CI Search", category: "files", status: "planned",
    description: "One semantic search across mail, files, PDFs, chats, records and systems.",
    keywords: ["search", "find", "lookup"] },
  { id: "ci-scan", slug: "scan", name: "CI Scan", category: "files", status: "planned",
    description: "Camera/scanner capture, OCR, receipt detection, automatic filing.",
    keywords: ["scan", "ocr", "camera"] },
  { id: "ci-sign", slug: "sign", name: "CI Sign", replaces: "DocuSign", category: "files", status: "planned",
    description: "E-signatures, approval chains, audit trails, reusable templates.",
    keywords: ["signature", "docusign", "esign"] },
  { id: "ci-archive", slug: "archive", name: "CI Archive", category: "files", status: "planned",
    description: "Long-term retention, immutable records, legal hold policies.",
    keywords: ["archive", "retention", "legal hold"] },

  // ── Business ────────────────────────────────────────────────────────
  { id: "ci-crm", slug: "crm", name: "CI CRM", category: "business", status: "live",
    description: "Leads, pipelines, opportunities, customer timeline, AI sales assistance.",
    keywords: ["crm", "sales", "leads", "pipeline", "customer"] },
  { id: "ci-projects", slug: "projects", name: "CI Projects", category: "business", status: "live",
    description: "Kanban, timeline/Gantt, milestones, workload, budgets, time tracking.",
    keywords: ["projects", "kanban", "gantt", "milestones"] },
  { id: "ci-sales", slug: "sales", name: "CI Sales", category: "business", status: "live",
    description: "Quotations, price lists, orders, commissions, sales targets.",
    keywords: ["sales", "quotation", "orders"] },
  { id: "ci-customer-service", slug: "customer-service", name: "CI Customer Service", category: "business", status: "live",
    description: "Tickets, SLAs, canned responses, knowledge base, AI support agents.",
    keywords: ["help desk", "support", "tickets", "sla"] },
  { id: "ci-marketing", slug: "marketing", name: "CI Marketing", category: "business", status: "planned",
    description: "Campaigns, contact lists, landing pages, segmentation, automation.",
    keywords: ["marketing", "campaign", "email marketing"] },
  { id: "ci-erp-core", slug: "erp", name: "CI ERP Core", category: "business", status: "planned",
    description: "Companies, branches, currencies, taxes, fiscal periods, master data.",
    keywords: ["erp", "master data", "fiscal"] },
  { id: "ci-accounting", slug: "accounting", name: "CI Accounting & Finance", category: "business", status: "planned",
    description: "General ledger, receivables/payables, banking, budgets, AI anomaly detection.",
    keywords: ["accounting", "finance", "ledger", "budget"] },
  { id: "ci-invoicing", slug: "invoicing", name: "CI Invoicing", category: "business", status: "live",
    description: "Estimates, invoices, credit notes, recurring billing, payment links.",
    keywords: ["invoice", "billing", "estimate"] },
  { id: "ci-purchasing", slug: "purchasing", name: "CI Purchasing", category: "business", status: "planned",
    description: "Purchase requests, RFQs, supplier comparison, approvals, POs.",
    keywords: ["procurement", "purchasing", "rfq", "purchase order"] },
  { id: "ci-inventory", slug: "inventory", name: "CI Inventory", category: "business", status: "planned",
    description: "SKUs, warehouses, stock movements, lot/serial, reorder points, valuation.",
    keywords: ["inventory", "warehouse", "stock"] },
  { id: "ci-pos", slug: "pos", name: "CI POS", category: "business", status: "planned",
    description: "Retail sales, cash drawers, discounts, offline mode, branch sync.",
    keywords: ["pos", "point of sale", "retail"] },
  { id: "ci-manufacturing", slug: "manufacturing", name: "CI Manufacturing", category: "business", status: "planned",
    description: "BOMs, production orders, routing, capacity planning, quality checks.",
    keywords: ["manufacturing", "bom", "production"] },
  { id: "ci-logistics", slug: "logistics", name: "CI Logistics", category: "business", status: "planned",
    description: "Deliveries, routes, drivers, proof of delivery, dispatch planning.",
    keywords: ["logistics", "delivery", "fleet", "dispatch"] },
  { id: "ci-hr", slug: "hr", name: "CI HR", category: "business", status: "planned",
    description: "Employee profiles, org chart, onboarding, leave, evaluations, self-service.",
    keywords: ["hr", "human resources", "employee", "onboarding"] },
  { id: "ci-payroll", slug: "payroll", name: "CI Payroll", category: "business", status: "planned",
    description: "Salaries, deductions, bonuses, payroll runs, payslips, accounting sync.",
    keywords: ["payroll", "salary", "payslip"] },
  { id: "ci-attendance", slug: "attendance", name: "CI Attendance", category: "business", status: "planned",
    description: "Clock-in/out, shifts, schedules, overtime, absence tracking.",
    keywords: ["attendance", "clock in", "shifts"] },
  { id: "ci-recruit", slug: "recruit", name: "CI Recruit", category: "business", status: "planned",
    description: "Vacancies, applicants, CV parsing, interviews, offers, onboarding handoff.",
    keywords: ["recruiting", "hiring", "applicant"] },
  { id: "ci-maintenance", slug: "maintenance", name: "CI Maintenance", category: "business", status: "planned",
    description: "Preventive maintenance, work orders, equipment history, spare parts.",
    keywords: ["maintenance", "work order", "equipment"] },
  { id: "ci-contracts", slug: "contracts", name: "CI Contracts", category: "business", status: "planned",
    description: "Contracts, renewal dates, clauses, versioning, AI contract extraction.",
    keywords: ["contracts", "renewal", "legal"] },
  { id: "ci-portals", slug: "portals", name: "CI Portals", category: "business", status: "planned",
    description: "Customer, supplier, employee and partner self-service portals.",
    keywords: ["portal", "self-service"] },

  // ── Create ──────────────────────────────────────────────────────────
  { id: "ci-design", slug: "design", name: "CI Design", category: "create", status: "planned",
    description: "Banners, ads, social posts, brochures, branded templates, image generation.",
    keywords: ["design", "graphics", "canva"] },
  { id: "ci-media", slug: "media", name: "CI Media", category: "create", status: "planned",
    description: "Image/audio/video library, transcoding, metadata, AI search.",
    keywords: ["media library", "assets"] },
  { id: "ci-video", slug: "video", name: "CI Video", category: "create", status: "planned",
    description: "Video editing, subtitles, transcription, brand templates, AI production.",
    keywords: ["video editing", "subtitles"] },
  { id: "ci-audio", slug: "audio", name: "CI Audio", category: "create", status: "planned",
    description: "Recording, voice notes, transcription, translation, speech generation.",
    keywords: ["audio", "voice", "transcription"] },
  { id: "ci-translate", slug: "translate", name: "CI Translate", category: "create", status: "planned",
    description: "Documents, messages, websites and subtitles translated with formatting kept.",
    keywords: ["translate", "translation", "language"] },
  { id: "ci-website", slug: "website", name: "CI Website / Commerce", category: "create", status: "planned",
    description: "Websites, landing pages, catalogues, online stores, checkout.",
    keywords: ["website", "ecommerce", "landing page", "store"] },

  // ── IT ──────────────────────────────────────────────────────────────
  { id: "ci-remote", slug: "remote", name: "CI Remote", category: "it", status: "planned",
    description: "Remote desktop/support, screen sharing, unattended access, diagnostics.",
    keywords: ["remote desktop", "remote support"] },
  { id: "ci-it-desk", slug: "it-desk", name: "CI IT Desk", category: "it", status: "planned",
    description: "IT tickets, troubleshooting, device records, software inventory.",
    keywords: ["it support", "helpdesk", "tickets"] },
  { id: "ci-devices", slug: "devices", name: "CI Device Management", category: "it", status: "planned",
    description: "Enrollment, configuration, updates, compliance, remote lock/wipe.",
    keywords: ["mdm", "device management", "endpoint"] },
  { id: "ci-software-center", slug: "software-center", name: "CI Software Center", category: "it", status: "planned",
    description: "Approved application catalog, install/update/remove, license tracking.",
    keywords: ["app catalog", "software deployment"] },
  { id: "ci-patch", slug: "patch", name: "CI Patch / Update", category: "it", status: "planned",
    description: "OS/app update monitoring, vulnerabilities, deployment rings, rollback.",
    keywords: ["patching", "updates", "vulnerabilities"] },
  { id: "ci-security-center", slug: "security", name: "CI Security Center", category: "it", status: "planned",
    description: "Security alerts, identity risk, endpoint status, incident workflows.",
    keywords: ["security", "soc", "incidents"] },
  { id: "ci-backup", slug: "backup", name: "CI Backup", category: "it", status: "planned",
    description: "Endpoint/file/database backup, retention, snapshots, disaster recovery.",
    keywords: ["backup", "disaster recovery", "restore"] },
  { id: "ci-print", slug: "print", name: "CI Print", category: "it", status: "planned",
    description: "Printer management, queues, templates, label and barcode printing.",
    keywords: ["print", "printer", "label"] },
  { id: "ci-browser", slug: "browser", name: "CI Browser", category: "it", status: "planned",
    description: "Secure company browser/workspace with AI page understanding and capture.",
    keywords: ["browser", "secure browsing"] },
  { id: "ci-offline", slug: "offline", name: "CI Offline", category: "it", status: "planned",
    description: "Local cache, offline documents, queued changes, sync on reconnect.",
    keywords: ["offline", "sync"] },
  { id: "ci-assets", slug: "assets", name: "CI Assets", category: "it", status: "planned",
    description: "PCs, phones, vehicles, machinery, licenses, warranties, depreciation links.",
    keywords: ["asset management", "equipment"] },

  // ── Build ───────────────────────────────────────────────────────────
  { id: "ci-database", slug: "database", name: "CI Database", category: "build", status: "planned",
    description: "No-code tables, relational data, custom fields, views, APIs.",
    keywords: ["database", "airtable", "no-code"] },
  { id: "ci-builder", slug: "builder", name: "CI Builder", category: "build", status: "planned",
    description: "Company-specific mini-apps: forms, tables, dashboards, portals, no code.",
    keywords: ["app builder", "low-code", "no-code"] },
  { id: "ci-automate", slug: "automate", name: "CI Automate", replaces: "Zapier / Power Automate", category: "build", status: "planned",
    description: "Triggers, conditions, actions, webhooks, agent-powered automations.",
    keywords: ["automation", "zapier", "workflow", "webhook"] },
  { id: "ci-workflow-engine", slug: "workflow", name: "CI Workflow Engine", category: "build", status: "planned",
    description: "Business process stages, rules, escalation, delegation, cross-module flows.",
    keywords: ["workflow", "bpm", "process"] },
  { id: "ci-api-hub", slug: "api-hub", name: "CI API Hub", category: "build", status: "planned",
    description: "External APIs, OAuth connections, webhooks, credentials, quotas, logs.",
    keywords: ["api", "integration", "oauth"] },
  { id: "ci-connect", slug: "connect", name: "CI Connect", category: "build", status: "planned",
    description: "Connectors to Microsoft, Google, banks, e-commerce, CRMs and more.",
    keywords: ["integrations", "connectors"] },
  { id: "ci-data-hub", slug: "data-hub", name: "CI Data Hub", category: "build", status: "planned",
    description: "Import/export, ETL, mapping, sync, dedup, master-data management.",
    keywords: ["etl", "data pipeline", "sync"] },
  { id: "ci-dev", slug: "dev", name: "CI Dev", category: "build", status: "planned",
    description: "Developer workspace: editor, repos, terminals, environments, AI coding.",
    keywords: ["developer", "code editor", "ide"] },
  { id: "ci-marketplace", slug: "marketplace", name: "CI Marketplace", category: "build", status: "planned",
    description: "Install additional modules, industry packs, connectors, agent skills.",
    keywords: ["marketplace", "extensions", "add-ons"] },
  { id: "ci-industry-packs", slug: "industry-packs", name: "CI Industry Packs", category: "build", status: "planned",
    description: "Pre-built packages for retail, hospitality, medical admin, construction and more.",
    keywords: ["industry pack", "vertical", "template"] },

  // ── Intelligence ────────────────────────────────────────────────────
  { id: "ci-assistant", slug: "assistant", name: "CI Assistant", category: "intelligence", status: "planned",
    description: "The universal conversational interface, available everywhere in the OS.",
    keywords: ["assistant", "chatbot", "ai"] },
  { id: "ci-agents", slug: "agents", name: "CI Agents", category: "intelligence", status: "planned",
    description: "Specialized agents: GM, HR, Sales, Accounting, Procurement, Support, Legal.",
    keywords: ["agents", "ai agents"] },
  { id: "ci-agent-studio", slug: "agent-studio", name: "CI Agent Studio", category: "intelligence", status: "planned",
    description: "Build an agent: instructions, knowledge, tools, permissions, thresholds.",
    keywords: ["agent builder", "agent studio"] },
  { id: "ci-knowledge", slug: "knowledge", name: "CI Knowledge", category: "intelligence", status: "planned",
    description: "Internal wiki, procedures, manuals, FAQs, SOPs, knowledge graph.",
    keywords: ["wiki", "knowledge base", "sop"] },
  { id: "ci-ocr", slug: "ocr", name: "CI OCR / Document Intelligence", category: "intelligence", status: "planned",
    description: "Extract structured records from invoices, receipts, IDs, contracts, forms.",
    keywords: ["ocr", "document intelligence", "extraction"] },
  { id: "ci-intelligence-core", slug: "intelligence-core", name: "CI Intelligence Core", category: "intelligence", status: "planned",
    description: "The reasoning substrate: context, retrieval, multimodal understanding, model routing.",
    keywords: ["ai core", "reasoning", "model routing"] },
  { id: "ci-memory", slug: "memory", name: "CI Memory / Knowledge Graph", category: "intelligence", status: "planned",
    description: "Relationships between customers, suppliers, employees, documents, events.",
    keywords: ["knowledge graph", "memory", "relationships"] },
  { id: "ci-orchestrator", slug: "orchestrator", name: "CI Orchestrator", category: "intelligence", status: "planned",
    description: "Takes a business objective and decides which modules/agents must cooperate.",
    keywords: ["orchestration", "planner"] },
  { id: "ci-voice", slug: "voice", name: "CI Voice", category: "intelligence", status: "planned",
    description: "Natural voice interaction with the OS — \"show me today's payments.\"",
    keywords: ["voice", "speech"] },

  // ── Control ─────────────────────────────────────────────────────────
  { id: "ci-legal", slug: "legal", name: "CI Legal / Compliance", category: "control", status: "planned",
    description: "Policies, regulatory documents, audit trails, risk registers, evidence.",
    keywords: ["legal", "compliance", "risk"] },
  { id: "ci-approval-center", slug: "approvals", name: "CI Approval Center", category: "control", status: "live",
    description: "One place for every approval: invoices, purchases, contracts, leave, agent actions.",
    keywords: ["approvals", "sign-off"] },
  { id: "ci-identity", slug: "identity", name: "CI Identity", category: "control", status: "planned",
    description: "Users, groups, roles, SSO, MFA, passkeys, sessions, auth policies.",
    keywords: ["identity", "sso", "mfa", "auth"] },
  { id: "ci-vault", slug: "vault", name: "CI Vault", category: "control", status: "planned",
    description: "Passwords, API keys, certificates, secure notes, controlled agent access.",
    keywords: ["vault", "secrets", "password manager"] },
  { id: "ci-permissions", slug: "permissions", name: "CI Permissions", category: "control", status: "planned",
    description: "Fine-grained RBAC/ABAC across every module, including agent actions.",
    keywords: ["rbac", "permissions", "access control"] },
  { id: "ci-admin-center", slug: "admin", name: "CI Admin Center", category: "control", status: "planned",
    description: "Company setup, branches, subscriptions, branding, policies, integrations.",
    keywords: ["admin", "settings", "tenant"] },
  { id: "ci-audit", slug: "audit", name: "CI Audit", category: "control", status: "live",
    description: "Immutable history of who did what, when, and whether it was human or agent.",
    keywords: ["audit log", "history"] },
  { id: "ci-governance", slug: "governance", name: "CI Governance", category: "control", status: "planned",
    description: "Data classification, retention, AI policy, privacy, org-wide rules.",
    keywords: ["governance", "data policy"] },
  { id: "ci-autonomy-control", slug: "autonomy", name: "CI Autonomy Control", category: "control", status: "planned",
    description: "What CI may do automatically, what needs approval, what it must never do.",
    keywords: ["autonomy", "guardrails", "ai policy"] },
  { id: "ci-activity-trace", slug: "activity", name: "CI Activity / Trace", category: "control", status: "planned",
    description: "Readable timeline of every step CI and its agents took to reach a result.",
    keywords: ["trace", "activity log", "agent trace"] },

  // ── Executive ───────────────────────────────────────────────────────
  { id: "ci-bi", slug: "bi", name: "CI Business Intelligence", category: "executive", status: "planned",
    description: "Dashboards, KPIs, drill-down, forecasting, natural-language questions.",
    keywords: ["bi", "analytics", "dashboard", "kpi"] },
  { id: "ci-control-room", slug: "control-room", name: "CI Control Room", category: "executive", status: "planned",
    description: "Owner/GM view: sales, money, staff, stock, operations, risks, agents, alerts.",
    keywords: ["control room", "executive dashboard"] },
];

export function getModule(slug: string): ModuleDefinition | undefined {
  return MODULES.find((m) => m.slug === slug);
}

export function modulesByCategory(category: string): ModuleDefinition[] {
  return MODULES.filter((m) => m.category === category);
}

export function searchModules(query: string): ModuleDefinition[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return MODULES.filter(
    (m) =>
      m.name.toLowerCase().includes(q) ||
      m.description.toLowerCase().includes(q) ||
      m.keywords.some((k) => k.includes(q)) ||
      (m.replaces ?? "").toLowerCase().includes(q)
  );
}
